# Generated by Django 4.1 on 2022-08-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_books_book_image_store_store_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_image',
            field=models.ImageField(default='default.jpg', upload_to='Book_Images'),
        ),
    ]
